# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */ #

# ==============================
# Theme
# ==============================
include ./kitty-themes/00-Default.conf

# ==============================
# Font
# ==============================
font_family      Fira Code
# Or if you installed the Nerd Font version:
# font_family      FiraCode Nerd Font

font_size        18.0

# modify_font underline_position -2
# modify_font underline_thickness 150%
# modify_font strikethrough_position 2px

# This adds a bit of vertical space between lines (adjust to taste)
adjust_line_height  100%
# ==============================
#
# Colors
# ==============================
foreground #dddddd
background #000000
cursor #dddddd

selection_foreground none
selection_background none

# ==============================
# Opacity
# ==============================
background_opacity 0.925
dynamic_background_opacity yes

# ==============================
# Cursor (✨ PRO animated setup)
# ==============================
cursor_shape block
cursor_blink false
# ==============================
# Performance / Latency
# ==============================
input_delay 0
repaint_delay 8
sync_to_monitor yes

# ==============================
# Scrolling
# ==============================
scrollback_lines 5000
wheel_scroll_min_lines 1
wheel_scroll_multiplier 3.0
touch_scroll_multiplier 3.0

# ==============================
# Window behavior
# ==============================
window_padding_width 
confirm_os_window_close 0
hide_window_decorations yes

# ==============================
# System
# ==============================
linux_display_server auto
enable_audio_bell no
