add_newline = true
format = """
$directory\
$git_branch\
$python\
$line_break\
$character
"""

[line_break]
disabled = false

[cmd_duration]
disabled = true

[directory]
style = "fg:#88c0d0"
format = "[$path]($style) "
truncation_length = 1

[git_branch]
symbol = " "
style = "fg:#bf616a"
format = "$symbol[\\[$branch\\]]($style) "

[python]
symbol = " "
style = "fg:#ebcb8b"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[character]
success_symbol = "[❯](fg:#88C0D0)"
error_symbol = "[❯](fg:#bf616a)"
