[manager]
# ~/.config/yazi/theme.toml
# The line your cursor is on
hovered = { fg = "#1C1917", bg = "#6099C0", bold = true }

# The border between panes
border_style = { fg = "#3D3833" }

[status]
# The bar at the very bottom
progress_normal = { fg = "#6099C0", bg = "#3D3833" }
progress_error = { fg = "#e67e80", bg = "#3D3833" }
permissions = { fg = "#6099C0" }

[filetype]
rules = [
	# Folders in Zenbones Blue
	{ mime = "directory", fg = "#6099C0" },
	# Executables in Zenbones Green/Cyan
	{ mime = "application/*", fg = "#819B69" },
]
